repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      # Run the linter.
      - id: pytest
        name: pytest
        entry: poetry
        args: [ 'run', 'python', '-m', 'pytest', '--testmon' ]
        language: system
        types: [ python ]
        require_serial: true
        pass_filenames: false
